function Hd = notch_comb
%NOTCH_COMB Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 08-Oct-2018 13:39:47

% IIR Comb Notching filter designed using the IIRCOMB function.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

N     = 6;  % Order
Q     = 3;  % Q-factor
Apass = 1;  % Bandwidth Attenuation

BW = 2*Fs/2/6/Q;

% Calculate the coefficients using the IIRCOMB function.
[b, a] = iircomb(N, BW/(Fs/2), Apass);
Hd = dsp.IIRFilter( ...
    'Structure', 'Direct form II', ...
    'Numerator', b, ...
    'Denominator', a);

% [EOF]
