function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 19-Sep-2018 11:43:20

N     = 6;     % Order
F3dB1 = 59;    % First
F3dB2 = 61;    % Second
Fs    = 1000;  % Sampling Frequency

h = fdesign.bandstop('n,f3db1,f3db2', N, F3dB1, F3dB2, Fs);

Hd = design(h, 'butter', ...
    'SystemObject', true);


