function Hd = notch
%NOTCH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 02-Oct-2018 15:26:24

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.

% [EOF]
