function Hd = test_notch
%TEST_NOTCH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 01-Oct-2018 21:12:11

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

Fnotch = 60;  % Notch Frequency
BW     = 30;  % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd = dsp.IIRFilter( ...
    'Structure', 'Direct form II', ...
    'Numerator', b, ...
    'Denominator', a);

% [EOF]
